# Generated by Django 4.2.13 on 2024-06-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
